### ISSUE TITLE
JavaScript crash with error "$ is not a function..." for pages that use <gf:bootstrapCalendar>

### ISSUE THREAD

**Issue by aosipenko-sc** [OpusCapita/grailsflow-core-plugin#28]
JavaScript doesn't work on pages which required module "grailsflowDatepicker" and used tag <gf:bootstrapCalendar>.

**Comment by azinchenko-sc** [comment]
While researching the issue it was discovered that in `/processList` page we have the problem when date picker will not be initialized after migration from **JSCal2** to **Bootstrap** calendar(GFW-389). This problem is more complicated and requires to rethink concept of dynamic search criteria implementation: currently it loads datepicker component and initialized it after page is loaded (when it doesn't exists in DOM and will be added dynamically via JS).

**Comment by ivouchak-sc** [comment]
The issue was fixed.
